name: chart_components
description: Two chart components for Flutter. Animated bar chart and animated calendar grid chart based on the github's one. Many properties to customize.
version: 1.0.1
authors:
  - Fernando Paredes Quesada<fgcan10@gmail.com>
homepage: https://github.com/fgcan10/chart_components

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
